//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingDownloader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BingDownloader.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icons8_bing {
            get {
                object obj = ResourceManager.GetObject("icons8_bing", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icons8_bing_128 {
            get {
                object obj = ResourceManager.GetObject("icons8_bing_128", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html&gt;&lt;head&gt;&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;&lt;title&gt;LAYOUT DETALHADO&lt;/title&gt;&lt;style type=&quot;text/css&quot;&gt;table { width: 90%; border-spacing: 2px; margin-left: auto; margin-right: auto; }caption { color: #33ccff; font-size: 50px; font-style: italic; font-weight: bold; }td { width: 50%; }div { height: 100px; border: 1px solid; padding: 5px; border-radius: 20px; display: inherit; }img { float: left; padding: 5px; }.c5 { color: cor01; }.c6 { color: cor02; }.c7 { color: cor03; }.c8 { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string layout1 {
            get {
                return ResourceManager.GetString("layout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html&gt;&lt;head&gt;&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;&lt;title&gt;LAYOUT COMPACTO&lt;/title&gt;&lt;style type=&quot;text/css&quot;&gt;table { width: 90%; border-spacing: 2px; margin-left: auto; margin-right: auto; }caption { color: #33ccff; font-size: 50px; font-style: italic; font-weight: bold; }td { padding: 5; vertical-align: top; max-width: 20%; word-break: break-all; text-align: center; }div { border: 1px solid; padding: 5px; border-radius: 20px; }img { padding: 5px; }.c4 { color: cor01; }.c5 { color: c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string layout2 {
            get {
                return ResourceManager.GetString("layout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap safe_in_48 {
            get {
                object obj = ResourceManager.GetObject("safe_in_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thumbs {
            get {
                object obj = ResourceManager.GetObject("thumbs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
